name: Code Quality Metrics

on: 
  push:
    paths:
      - 'page_limits/**'
      - 'tests/**'

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  pylint:
    if: github.actor != 'github-actions'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install common dependencies
      run: |
        python -m pip install --upgrade pip
        mkdir -p metrics
        mkdir -p metrics/coverage
        
    - name: Analysing the code with pylint
      run: |
        pip install pylint pylint-report
        pylint page_limits | pylint_report > metrics/pylint_resume.html
        
    - name: Testing and test analysis
      run: |
        pip install pytest pytest-html pytest-cov
        pip install opencv-python matplotlib opencv-contrib-python scipy
        pytest --html=metrics/test_report.html --self-contained-html
        pytest --cov=page_limits --cov-report=html:metrics/coverage

    - name: Code documentation analysis
      run: |
        pip install docstr-coverage
        docstr-coverage page_limits >> metrics/docstring_coverage_report.txt 2>&1 || true

    - name: Cyclomatic and raw ode metrics
      run: |
        sudo apt-get update && sudo apt-get install -y pandoc
        pip install radon
        radon cc -a --md --min B -O metrics/cyclomatic_complexity.md page_limits
        pandoc metrics/cyclomatic_complexity.md -o metrics/cyclomatic_complexity.html
        radon raw -O metrics/raw_metrics.txt page_limits
        
    - name: Subir a Pages
      uses: actions/upload-pages-artifact@v3
      with:
        path: 'metrics'
    - name: Deploy to GitHub Pages
      uses: actions/deploy-pages@v4
