name: Pylint

on: 
  push:
    paths-ignore:
      - 'metrics/**'

  workflow_dispatch:

jobs:
  build:
    if: github.actor != 'github-actions'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint pylint-json2html pylint-report
    - name: Analysing the code with pylint
      run: |
        # pylint $(git ls-files '*.py') --output-format=json --exit-zero | pylint-json2html -o metrics/pylint_data.html
        # pylint $(git ls-files '*.py') --reports=y --score=y --output-format=text --exit-zero > metrics/pylint_resume.txt
        pylint page_limits | pylint_report > metrics/pylint_resume.html
    - name: Commit report to repo
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        git add metrics/pylint_data.html
        git add metrics/pylint_resume.txt
        git commit -m "Update pylint report" || echo "No changes to commit"
        git push
